// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrwi4eI8Uu_EL5B1odyytBSl9M3sDLaws',
    appId: '1:246477472500:web:c4c2d3f226463605f614a1',
    messagingSenderId: '246477472500',
    projectId: 'trendstylestore-25ee0',
    authDomain: 'trendstylestore-25ee0.firebaseapp.com',
    storageBucket: 'trendstylestore-25ee0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9rXkHfc8wseJcjQ-mKzl6tp5dx9ffZns',
    appId: '1:246477472500:android:af6004a3f1f30ffef614a1',
    messagingSenderId: '246477472500',
    projectId: 'trendstylestore-25ee0',
    storageBucket: 'trendstylestore-25ee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtDbyYJ2oLHlflKNlVOV_406OXo-I68p0',
    appId: '1:246477472500:ios:a395d2feacc74f29f614a1',
    messagingSenderId: '246477472500',
    projectId: 'trendstylestore-25ee0',
    storageBucket: 'trendstylestore-25ee0.appspot.com',
    androidClientId: '246477472500-dhlub07bvdn6bsfsc7bn66a5mum5g3o8.apps.googleusercontent.com',
    iosClientId: '246477472500-1dcjkjv4sratmv4kbh2c91hnl3ndmi7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendStyleStore',
  );

}